wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1646982714
    t:
      1:
      - 1
      - 5
      - 41
      2:
      - 1
      - 5
      - 41
      4: 3.8.10
      5: 0.12.11
      8:
      - 1
      - 5
