id:                             effnet_arcface_gem
pretrained:                     Null
model:
    name:                       BaseEffnetModel
    args:
        model_name:             tf_efficientnet_b0_ns
        embedding_size:         512
        num_classes:            15587
        s:                      30.0 
        m:                      0.50
        easy_margin:            False
        ls_eps:                 0.0
        freeze_backbone:        False 

optimizer:
    name:                       Adam
    args:
        lr:                     0.0001
loss:
    name:                       CrossEntropyLoss  
    args:                       Null
metric:
    -   name:                   MAP5
        args:                   Null
scheduler:
    name:                       CosineAnnealingLR
    args:
        T_max:                  500
        eta_min:                0.000001
dataset:
    num_folds:                  5
    folds_train_dir:            lists/folds/train/
    folds_test_dir:             lists/folds/val/
    train:
        name:                   HappyWhaleDataset
        args:
            data_dir:           data/happy-whale-and-dolphin/train_images/         
            csv_path:           lists/train.csv
            IMG_SIZE:           448
            is_train:           True  
        loader:
            name: DataLoader
            args:
                batch_size:     32
                shuffle:        True
                drop_last:      True 
    val:
        name:                   HappyWhaleDataset
        args:
            data_dir:           data/happy-whale-and-dolphin/train_images/         
            csv_path:           lists/train.csv
            IMG_SIZE:           448
            is_train:           False  
        loader:
            name: DataLoader
            args:
                batch_size:     64
                shuffle:        True

trainer: 
    nepochs: 4
    val_step: 1
    log_step: 1
